version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: lesson
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    command: postgres
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: lesson
      DB_PASSWORD: lesson
      DB_DATABASE: lesson
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: always