version: '3'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: lesson
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5433:5432"
    command: postgres
    restart: always